version: "3.9"

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=digital_department
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always # Automatically restart the container if it crashes
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres
volumes:
  postgres_data:
